### ISSUE TITLE
combine-errors error

### ISSUE THREAD

**Issue by atimms** [brentp/fraguracy#4]
Thanks for this interesting tool, I'm looking into some sequencer specific error profiles and had an issue when trying to combine the individual error files.

When I run combine-errors i.e. ./fraguracy combine-errors -f<fai> fraguracy-22-90139-1-errors.bed fraguracy-22-90140-1-errors.bed.

I get the error:
thread 'main' panicked at 'Error reading first interval from file: ParseIntError { kind: InvalidDigit }', src/combine_errors.rs:74:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by brentp** [comment]
Thanks for reporting! I botched that one. I haven't been using combine-errors, only combine-counts
Will you give this a try?
[fraguracy.gz](https://github.com/brentp/fraguracy/files/11172623/fraguracy.gz)

Happy to hear anything that would be helpful for you.

**Comment by brentp** [comment]
BTW, if you only have a few samples, you can run `fraguracy extract ... *.bam` then it will make combine-errors and combine-counts unnecessary.

**Comment by atimms** [comment]
thanks for getting back to me so quickly

**Comment by brentp** [comment]
I also pushed a new release for this: https://github.com/brentp/fraguracy/releases/tag/v0.1.6
Thanks again for reporting. Might be a few more rough edges but should be easily fixed.

**Comment by brentp** [comment]
this was still broken in v0.1.6, I just pushed v0.1.8 that actually fixes it.
